name: Price Checker

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  price-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run price checker
        run: node price-checker/run-bot.mjs
